Fix uri 10
Black-Dot-2024/cr-blackdot pull request #162
Opened 2024-05-27 23:14 UTC by UriGOPAR

#Portada de reporte

2024-05-27 23:47 UTC, ricardo020202 requested changes

2024-05-27 23:47 UTC, ricardo020202 commented on talent360/evaluaciones/models/evaluacion.py
> +            'type': 'ir.actions.report',
comillas dobles

2024-05-27 23:47 UTC, ricardo020202 commented on talent360/evaluaciones/views/portada_reporte_template.xml
> +                <h2 class="text-center">Fecha de expidición: <span t-esc="datetime.datetime.now().strftime('%Y-%m-%d')"/></h2>
expedición

2024-05-27 23:52 UTC, ricardo020202 approved these changes

2024-05-28 00:21 UTC, mafeermoreno approved these changes

2024-05-28 00:21 UTC, merged