RF51 Cambiar Semaforización
Black-Dot-2024/cr-blackdot pull request #175
Opened 2024-05-30 00:22 UTC by danfupo03

# RF51 Cambiar Semaforización

### Descripción
Rehacer la semaforización para hacerla dinámica. Esto implica hacer un modelo nuevo y hacer la conexión con los reportes para que las gráficas cambien de color de acuerdo a la semaforización. 

### Cambios realizados

- Nuevo modelo "Niveles"
- Relación entre Niveles-Evaluación
- Cambios en la UI de crear y resumen de evaluaciones en la parte de semaforización.
- Conexión de semaforización y los reportes

### Story Points

L - 5

### Criterios de aceptación

- [ ] El sistema permite modificar la cantidad de niveles de escala
- [ ] El sistema permite establecer los rangos de calificación con base a los nuevos niveles de escala 
- [ ] El sistema permite personalizar los colores de los niveles. 

### Definición de Done

- [X] Cumplimiento de todos los criterios de aceptación
- [ ] Pruebas realizadas y aprobadas
- [ ] Integración exitosa a la rama principal (main)
- [ ] Actualización de Plan de Valor Ganado
- [ ] Actualización de Matriz de Trazabilidad de Requerimientos

### Pruebas
Marcar pruebas realizadas. No es obligatorio hacer todas.
- [ ] Pruebas Unitarias
- [ ] Pruebas de Integración
- [ ] Pruebas de Sistema

2024-05-30 00:29 UTC, JP-coder2000 requested changes

2024-05-30 00:29 UTC, JP-coder2000 commented on talent360/evaluaciones/models/evaluacion.py
> +                        (0, 0, {"descripcion_nivel": "Regular", "techo": 60, "color": "#ebae14"}),
Esto es dinámico? Me puedes explicar como funciona?

2024-05-30 00:29 UTC, JP-coder2000 commented on talent360/evaluaciones/models/evaluacion.py
> +            # Verificar que el valor de la ponderación sea mayor que 0
Este comentario es del chat

2024-05-30 00:29 UTC, JP-coder2000 commented on talent360/evaluaciones/models/evaluacion.py
> +            # Verificar que no haya valores duplicados en la ponderación para la misma evaluación
CHAT GPT

ME HICE ADICTO A CHAAAAT GPT

2024-05-30 00:29 UTC, JP-coder2000 commented on talent360/evaluaciones/models/evaluacion.py
> +                    "El valor de la ponderación debe ser mayor que 0."
Mayor a 0, no mayor que 0

2024-05-30 00:29 UTC, JP-coder2000 commented on talent360/evaluaciones/views/reporte_clima_template.xml
> +                                        xmlns="http://www.w3.org/2000/svg">
Esto me parece raro, ese link, me puedes explicar?

2024-05-31 00:38 UTC, JP-coder2000 approved these changes

2024-05-31 00:38 UTC, DavidLangarica approved these changes

2024-05-31 00:38 UTC, merged