RF 56 | Agregar datos demográficos
Black-Dot-2024/cr-blackdot pull request #193
Opened 2024-06-03 17:39 UTC by DanielSebasCM

# RF 56 | Agregar datos demográficos

### Descripción
Como cliente de CR quiero agregar datos demográficos a mis empleados y que esto se refleje en los reportes

### Cambios realizados

- Cambio 1
- Cambio 2
- Cambio 3

### Story Points

M - 3

### Criterios de aceptación

- [x] El sistema precarga nuevos atributos de empleados. Ejm: Jefatura, Fecha de ingreso, etc.
- [x] La plantilla y carga de usuarios externos debe de expandirse para cargar los atributos creados dinámicamente
- [x] El sistema muestra estos datos demográficos en los reportes.
- [x] El sistema permite filtrar por estos nuevos atributos.
- [x] Los atributos que no tengan datos serán omitidos (si todos son N/A que no se muestren)

### Evidencias

### Definición de Done

- [ ] Cumplimiento de todos los criterios de aceptación
- [ ] Pruebas realizadas y aprobadas
- [ ] Integración exitosa a la rama principal (main)
- [ ] Actualización de Plan de Valor Ganado
- [ ] Actualización de Matriz de Trazabilidad de Requerimientos

### Pruebas
Marcar pruebas realizadas. No es obligatorio hacer todas.
- [ ] Pruebas Unitarias
- [x] Pruebas de Escenarios
- [ ] Pruebas de Sistema

2024-06-04 23:45 UTC, ricardo020202 requested changes

2024-06-04 23:45 UTC, ricardo020202 commented on talent360/evaluaciones/models/evaluacion.py
> +        ans = {}
esta en ingles

2024-06-04 23:45 UTC, ricardo020202 commented on talent360/evaluaciones/models/pregunta.py
> +        for record in self:
record esta en ingles

2024-06-04 23:45 UTC, ricardo020202 commented on talent360/evaluaciones/models/res_users.py
> +        print("atributos", atributos)
quita este print

2024-06-04 23:45 UTC, ricardo020202 commented on talent360/evaluaciones/models/usuario_externo.py
> +        for attr in atributos_extra:
ingles

2024-06-04 23:45 UTC, ricardo020202 commented on talent360/evaluaciones/models/usuario_externo.py
> +                f"Error al procesar el archivo: {str(e)}. Verifica que el archivo sea un CSV válido."
te falta el _

2024-06-04 23:45 UTC, ricardo020202 commented on talent360/evaluaciones/models/usuario_externo.py
> +            raise ValidationError(mensaje)
aqui igual el _

2024-06-04 23:45 UTC, ricardo020202 commented on talent360/evaluaciones/models/usuario_externo.py
> +                    f"El campo {campo} es requerido. Por favor verifica que todos los campos obligatorios estén presentes."
igual el _

2024-06-04 23:45 UTC, ricardo020202 commented on talent360/evaluaciones/wizards/asignar_usuarios_exernos_wizard.py
> +        csv_writer = csv.writer(datos)
esta en ingles

2024-06-04 23:45 UTC, ricardo020202 commented on talent360/evaluaciones/wizards/asignar_usuarios_exernos_wizard.py
> +        idx = len(datos_prueba_base)
si se puede mas descriptiva

2024-06-04 23:45 UTC, ricardo020202 commented on talent360/evaluaciones/wizards/asignar_usuarios_exernos_wizard.py
> +        csv_writer.writerow(datos_prueba_base)
ingles

2024-06-04 23:45 UTC, ricardo020202 commented on talent360/evaluaciones/wizards/asignar_usuarios_exernos_wizard.py
> +        attachment = self.env["ir.attachment"].search(
ingles

2024-06-04 23:45 UTC, ricardo020202 commented on talent360/evaluaciones/wizards/asignar_usuarios_exernos_wizard.py
> +        if attachment:
ingles

2024-06-05 00:19 UTC, ricardo020202 approved these changes

2024-06-05 00:57 UTC, DavidLangarica approved these changes
Listo

2024-06-05 00:58 UTC, merged