RF01 Creación de Evaluaciones 360
Black-Dot-2024/cr-blackdot pull request #25
Opened 2024-04-23 02:38 UTC by VON0222

# RF01 Creación de Evaluaciones 360

### Descripción
Como cliente de CR quiero crear evaluaciones 360 para tener una visión completa del rendimiento de cada colaborador.

### Cambios realizados

- Se crea el modelo evaluación 360 para crear evaluaciones 360
- Se crea la vista tipo form del modelo evaluación 360
- Se modifica el menú para incluir la evaluación 360
- Se modifica la vista tipo form del modelo evaluación
- Se agregan pruebas unitarias para el modelo de evaluación 360
- Se agregan los privilegios de los roles en el archivo ir.model.access.csv

### Story Points

M - 3

### Criterios de aceptación

- [ ] El sistema muestra el catálogo de competencias de evaluación.
- [ ] El sistema muestra la opción de agregar competencias a la evaluación.
- [ ] El sistema muestra la opción de eliminar competencias a la evaluación.
- [ ] El sistema muestra el catálogo de preguntas relacionadas con la competencia agregada a la evaluación.
- [ ] El sistema muestra el catálogo de preguntas incluidas en la evaluación.

### Evidencias

- Evidencia 1 [link]()
- Evidencia 2 [link]()

### Definición de Done

- [ ] Cumplimiento de todos los criterios de aceptación
- [ ] Pruebas realizadas y aprobadas
- [ ] Integración exitosa a la rama principal (main)
- [ ] Actualización de Plan de Valor Ganado
- [ ] Actualización de Matriz de Trazabilidad de Requerimientos

### Dependencias

Dependencias identificadas.

### Pruebas
Marcar pruebas realizadas. No es obligatorio hacer todas.
- [ ] Pruebas Unitarias
- [ ] Pruebas de Integración
- [ ] Pruebas de Sistema

2024-04-23 19:59 UTC, JP-coder2000 requested changes

2024-04-23 19:59 UTC, JP-coder2000 commented on talent360/evaluaciones/models/evaluacion.py
> +    # # do something on new usuario assigned
Hola!
Por favor si no van a utilizar este código no lo dejen comentado, borrenlo mejor, esto para que no pase a dev de esta forma, gracias!

2024-04-23 19:59 UTC, JP-coder2000 commented on talent360/evaluaciones/security/ir.model.access.csv
> +"access_opcion","access.opcion","model_opcion","base.group_user",1,1,1,1
Hola!
Por favor revisen la convención de como tienen que ir nombrados los permisos!

2024-04-23 19:59 UTC, JP-coder2000 commented on talent360/evaluaciones/security/security.xml
> +<?xml version="1.0" encoding="utf-8"?>
Hola!
Por favor revisen las convenciones para nombrar!

2024-04-23 19:59 UTC, JP-coder2000 commented on talent360/evaluaciones/views/evaluaciones_views.xml
> +
Hola!
Por favor revisen las convenciones para nombrar!

2024-04-24 00:46 UTC, DiegoSandovalV commented on talent360/evaluaciones/models/evaluacion.py
> +    # # do something on new usuario assigned
Se corrgió

2024-04-24 00:47 UTC, DiegoSandovalV commented on talent360/evaluaciones/security/ir.model.access.csv
> +"access_opcion","access.opcion","model_opcion","base.group_user",1,1,1,1
Es base de odoo

2024-04-24 01:11 UTC, DanielSebasCM approved these changes

2024-04-24 01:15 UTC, merged