RF14 & R40
Black-Dot-2024/cr-blackdot pull request #78
Opened 2024-05-09 17:59 UTC by dvegaa20

# Descripción
Se arregla el envio de correos
# Cambios Realizados
- No se contaba con el correo de origen para mandarlos

2024-05-09 18:06 UTC, ricardo020202 approved these changes
lgtm

2024-05-09 23:55 UTC, Riosmena approved these changes

2024-05-09 23:58 UTC, Riosmena requested changes
Creo que tiene conflictos

2024-05-10 00:08 UTC, alejandraa-cruiz approved these changes
Gracias

2024-05-10 00:12 UTC, Riosmena approved these changes

2024-05-10 00:12 UTC, merged