fix(security): granted correct access for colaboradores & clientes
Black-Dot-2024/cr-blackdot pull request #93
Opened 2024-05-10 17:41 UTC by dvegaa20

# Descripción
Se agregan los permisos correspondientes a colaboradores y clientes de CR

2024-05-10 18:58 UTC, alejandraa-cruiz approved these changes
Thanks

2024-05-10 20:36 UTC, alejandraa-cruiz requested changes

2024-05-10 20:36 UTC, alejandraa-cruiz commented on talent360/evaluaciones/security/ir.model.access.csv
> +"access_competencia_cliente_cr","access.competencia","model_competencia","evaluaciones.evaluaciones_cliente_cr_group_user",1,1,1,1
checar responder evaluaciones

2024-05-12 21:21 UTC, alejandraa-cruiz approved these changes

2024-05-12 22:03 UTC, JP-coder2000 approved these changes

2024-05-12 22:03 UTC, merged